"""create initial tables

Revision ID: bcf33111419a
Revises: 
Create Date: 2024-02-23 16:02:00.891049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bcf33111419a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('animals',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('animal_type', sa.String(), nullable=True),
    sa.Column('breed', sa.String(), nullable=True),
    sa.Column('city_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_animals_id'), 'animals', ['id'], unique=False)
    op.create_table('cats',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('favorite_fish', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['animals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dogs',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('bark_decibels', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['animals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dogs')
    op.drop_table('cats')
    op.drop_index(op.f('ix_animals_id'), table_name='animals')
    op.drop_table('animals')
    op.drop_table('cities')
    # ### end Alembic commands ###
